import { FlexibilityTest } from '../../types/flexibility';

export const FLEXIBILITY_TESTS: FlexibilityTest[] = [
  // Ankle Tests
  {
    id: 'ankle_dorsiflexion_left',
    name: 'Ankle Dorsiflexion (Left)',
    bodyPart: 'ankle',
    side: 'left',
    landmarks: [23, 25, 27],
    targetAngle: 45,
    minAcceptable: 30,
    instructions: 'Sit with leg extended. Pull toes toward shin while keeping knee straight.',
    holdDuration: 10,
  },
  {
    id: 'ankle_dorsiflexion_right',
    name: 'Ankle Dorsiflexion (Right)',
    bodyPart: 'ankle',
    side: 'right',
    landmarks: [24, 26, 28],
    targetAngle: 45,
    minAcceptable: 30,
    instructions: 'Sit with leg extended. Pull toes toward shin while keeping knee straight.',
    holdDuration: 10,
  },
  {
    id: 'ankle_plantarflexion_left',
    name: 'Ankle Plantarflexion (Left)',
    bodyPart: 'ankle',
    side: 'left',
    landmarks: [25, 27, 31],
    targetAngle: 50,
    minAcceptable: 35,
    instructions: 'Sit with leg extended. Point toes away from shin.',
    holdDuration: 10,
  },
  {
    id: 'ankle_plantarflexion_right',
    name: 'Ankle Plantarflexion (Right)',
    bodyPart: 'ankle',
    side: 'right',
    landmarks: [26, 28, 32],
    targetAngle: 50,
    minAcceptable: 35,
    instructions: 'Sit with leg extended. Point toes away from shin.',
    holdDuration: 10,
  },
  
  // Knee Tests
  {
    id: 'knee_flexion_left',
    name: 'Knee Flexion (Left)',
    bodyPart: 'knee',
    side: 'left',
    landmarks: [23, 25, 27],
    targetAngle: 145,
    minAcceptable: 120,
    instructions: 'Sit with leg extended. Bend knee bringing heel toward buttocks.',
    holdDuration: 10,
  },
  {
    id: 'knee_flexion_right',
    name: 'Knee Flexion (Right)',
    bodyPart: 'knee',
    side: 'right',
    landmarks: [24, 26, 28],
    targetAngle: 145,
    minAcceptable: 120,
    instructions: 'Sit with leg extended. Bend knee bringing heel toward buttocks.',
    holdDuration: 10,
  },
  {
    id: 'knee_extension_left',
    name: 'Knee Extension (Left)',
    bodyPart: 'knee',
    side: 'left',
    landmarks: [23, 25, 27],
    targetAngle: 0,
    minAcceptable: -5,
    instructions: 'Sit with leg extended. Straighten knee as much as possible.',
    holdDuration: 10,
  },
  {
    id: 'knee_extension_right',
    name: 'Knee Extension (Right)',
    bodyPart: 'knee',
    side: 'right',
    landmarks: [24, 26, 28],
    targetAngle: 0,
    minAcceptable: -5,
    instructions: 'Sit with leg extended. Straighten knee as much as possible.',
    holdDuration: 10,
  },
  
  // Hip Tests
  {
    id: 'hip_flexion_left',
    name: 'Hip Flexion (Left)',
    bodyPart: 'hip',
    side: 'left',
    landmarks: [11, 23, 25],
    targetAngle: 130,
    minAcceptable: 100,
    instructions: 'Lie on back. Bring knee toward chest while keeping lower back flat.',
    holdDuration: 10,
  },
  {
    id: 'hip_flexion_right',
    name: 'Hip Flexion (Right)',
    bodyPart: 'hip',
    side: 'right',
    landmarks: [12, 24, 26],
    targetAngle: 130,
    minAcceptable: 100,
    instructions: 'Lie on back. Bring knee toward chest while keeping lower back flat.',
    holdDuration: 10,
  },
  {
    id: 'hip_extension_left',
    name: 'Hip Extension (Left)',
    bodyPart: 'hip',
    side: 'left',
    landmarks: [11, 23, 25],
    targetAngle: 30,
    minAcceptable: 15,
    instructions: 'Lie on stomach. Lift leg behind you while keeping knee straight.',
    holdDuration: 10,
  },
  {
    id: 'hip_extension_right',
    name: 'Hip Extension (Right)',
    bodyPart: 'hip',
    side: 'right',
    landmarks: [12, 24, 26],
    targetAngle: 30,
    minAcceptable: 15,
    instructions: 'Lie on stomach. Lift leg behind you while keeping knee straight.',
    holdDuration: 10,
  },
  {
    id: 'hip_abduction_left',
    name: 'Hip Abduction (Left)',
    bodyPart: 'hip',
    side: 'left',
    landmarks: [24, 23, 25],
    targetAngle: 45,
    minAcceptable: 30,
    instructions: 'Lie on side. Lift leg outward to the side.',
    holdDuration: 10,
  },
  {
    id: 'hip_abduction_right',
    name: 'Hip Abduction (Right)',
    bodyPart: 'hip',
    side: 'right',
    landmarks: [23, 24, 26],
    targetAngle: 45,
    minAcceptable: 30,
    instructions: 'Lie on side. Lift leg outward to the side.',
    holdDuration: 10,
  },
  {
    id: 'hip_adduction_left',
    name: 'Hip Adduction (Left)',
    bodyPart: 'hip',
    side: 'left',
    landmarks: [24, 23, 25],
    targetAngle: 30,
    minAcceptable: 15,
    instructions: 'Lie on side with top leg bent. Lower bottom leg toward ground.',
    holdDuration: 10,
  },
  {
    id: 'hip_adduction_right',
    name: 'Hip Adduction (Right)',
    bodyPart: 'hip',
    side: 'right',
    landmarks: [23, 24, 26],
    targetAngle: 30,
    minAcceptable: 15,
    instructions: 'Lie on side with top leg bent. Lower bottom leg toward ground.',
    holdDuration: 10,
  },
  
  // Spine Tests
  {
    id: 'spine_flexion',
    name: 'Trunk Flexion (Sit & Reach)',
    bodyPart: 'spine',
    side: 'center',
    landmarks: [11, 23, 25],
    targetAngle: 85,
    minAcceptable: 60,
    instructions: 'Sit with legs extended. Reach forward keeping back straight.',
    holdDuration: 15,
  },
  {
    id: 'spine_extension',
    name: 'Trunk Extension',
    bodyPart: 'spine',
    side: 'center',
    landmarks: [11, 23, 25],
    targetAngle: 30,
    minAcceptable: 15,
    instructions: 'Lie on stomach. Lift chest and arms off the ground.',
    holdDuration: 10,
  },
  
  // Shoulder Tests
  {
    id: 'shoulder_flexion_left',
    name: 'Shoulder Flexion (Left)',
    bodyPart: 'shoulder',
    side: 'left',
    landmarks: [23, 11, 13],
    targetAngle: 175,
    minAcceptable: 150,
    instructions: 'Stand. Raise arm forward over head.',
    holdDuration: 10,
  },
  {
    id: 'shoulder_flexion_right',
    name: 'Shoulder Flexion (Right)',
    bodyPart: 'shoulder',
    side: 'right',
    landmarks: [24, 12, 14],
    targetAngle: 175,
    minAcceptable: 150,
    instructions: 'Stand. Raise arm forward over head.',
    holdDuration: 10,
  },
  {
    id: 'shoulder_extension_left',
    name: 'Shoulder Extension (Left)',
    bodyPart: 'shoulder',
    side: 'left',
    landmarks: [23, 11, 13],
    targetAngle: 55,
    minAcceptable: 35,
    instructions: 'Stand. Reach arm behind back.',
    holdDuration: 10,
  },
  {
    id: 'shoulder_extension_right',
    name: 'Shoulder Extension (Right)',
    bodyPart: 'shoulder',
    side: 'right',
    landmarks: [24, 12, 14],
    targetAngle: 55,
    minAcceptable: 35,
    instructions: 'Stand. Reach arm behind back.',
    holdDuration: 10,
  },
  
  // Elbow Tests
  {
    id: 'elbow_flexion_left',
    name: 'Elbow Flexion (Left)',
    bodyPart: 'elbow',
    side: 'left',
    landmarks: [11, 13, 15],
    targetAngle: 155,
    minAcceptable: 130,
    instructions: 'Stand with arm extended. Bend elbow bringing hand toward shoulder.',
    holdDuration: 10,
  },
  {
    id: 'elbow_flexion_right',
    name: 'Elbow Flexion (Right)',
    bodyPart: 'elbow',
    side: 'right',
    landmarks: [12, 14, 16],
    targetAngle: 155,
    minAcceptable: 130,
    instructions: 'Stand with arm extended. Bend elbow bringing hand toward shoulder.',
    holdDuration: 10,
  },
  {
    id: 'elbow_extension_left',
    name: 'Elbow Extension (Left)',
    bodyPart: 'elbow',
    side: 'left',
    landmarks: [11, 13, 15],
    targetAngle: 0,
    minAcceptable: -5,
    instructions: 'Stand with arm bent. Straighten elbow completely.',
    holdDuration: 10,
  },
  {
    id: 'elbow_extension_right',
    name: 'Elbow Extension (Right)',
    bodyPart: 'elbow',
    side: 'right',
    landmarks: [12, 14, 16],
    targetAngle: 0,
    minAcceptable: -5,
    instructions: 'Stand with arm bent. Straighten elbow completely.',
    holdDuration: 10,
  },
];

export const QUICK_TEST_IDS = [
  'hip_flexion_left',
  'hip_flexion_right',
  'spine_flexion',
  'shoulder_flexion_left',
  'shoulder_flexion_right',
  'knee_flexion_left',
  'knee_flexion_right',
  'ankle_dorsiflexion_left',
];

export function getTestById(id: string): FlexibilityTest | undefined {
  return FLEXIBILITY_TESTS.find(test => test.id === id);
}

export function getTestsByBodyPart(bodyPart: string): FlexibilityTest[] {
  return FLEXIBILITY_TESTS.filter(test => test.bodyPart === bodyPart);
}

export function getQuickTests(): FlexibilityTest[] {
  return FLEXIBILITY_TESTS.filter(test => QUICK_TEST_IDS.includes(test.id));
}

export function getAllTests(): FlexibilityTest[] {
  return FLEXIBILITY_TESTS;
}
